### ISSUE TITLE
GLITCHERS

### ISSUE THREAD

**Issue by John2949** [southpacificairways/.github#2]
At punta, there is a way for glitchers to glitch with /e dance. They can glitch through this wall

![RobloxPlayerBeta_QMd6oU04Hx](https://github.com/southpacificairways/.github/assets/157930599/02fa22cb-6b03-43ac-8509-4b78899611de)

**Comment by metricrb** [comment]
This is down to our building team whom haven't solved that in about 2 years, thus I assume they have no intention to do so.
