### ISSUE TITLE
PAX can't join.

### ISSUE THREAD

**Issue by John2949** [southpacificairways/.github#5]
**Describe the bug**
PAX cannot join punta cana.

**To Reproduce**
I don't know if there's a way to reproduce this, during 10 PM flight. Passengers were really pissed.

https://github.com/southpacificairways/.github/assets/157930599/30db28d5-67d9-4d9c-9a08-1b0aae57524c

**Expected behavior**
I expect this to be fixed ASAP as we are leaving passengers.

**Screenshots**
Video sent.

**Desktop (please complete the following information):**
Window 11, and tablet issue.

**Additional context**
N/A

**Comment by metricrb** [comment]
Not certain the root due to no output, if no reproduction then it'll be closed.

**Comment by John2949** [comment]
> Not certain the root due to no output, if no reproduction then it'll be closed.

Please take a look at this issue, as we had multiple complains regarding this. I am unsure how you can reproduce the root.
